In [1]:
import numpy as np
print(np.random.rand(5))

[0.21991327 0.32384582 0.62544656 0.34457317 0.55971623]


In [2]:
print(np.random.rand(5,2))

[[0.2845789  0.76763487]
 [0.22296099 0.45290827]
 [0.60513681 0.45669121]
 [0.37830389 0.23856245]
 [0.41551789 0.14164308]]


In [3]:
a =np.random.randint(1,10,5)
a

array([6, 1, 8, 3, 4], dtype=int32)

In [4]:
print(a.reshape(5,1))

[[6]
 [1]
 [8]
 [3]
 [4]]


In [5]:
arr_2d = np.array([[5,2,6],[10,2,9],[5,3,9]])
print(arr_2d)

[[ 5  2  6]
 [10  2  9]
 [ 5  3  9]]


In [6]:
#indexing in array
arr_2d[1,2]

np.int64(9)

In [7]:
arr_2d[:2,1:]

array([[2, 6],
       [2, 9]])

In [8]:
#conditional array
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
bool_arr = arr>5
print(bool_arr)
arr[bool_arr]

[False False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [10]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [11]:
print(arr_2d[1:3,3:5])

[[13 14]
 [23 24]]


In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [16]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#
np.random.rand(1)


array([0.33808209])

In [20]:
#
np.random.randn(25)

array([ 0.34844962,  0.75332683, -1.36117026,  1.60255393,  0.21240834,
        1.20562013, -0.20161893, -0.63480066,  0.16167671, -0.57972805,
       -0.13759562, -0.0806858 , -1.47539125,  0.06938896, -0.00192533,
       -0.22271153, -0.83697641,  0.44094281, -0.34438901,  1.38288074,
        0.49121347, -0.69595825, -0.6848107 , -0.28151665,  0.69952369])

In [21]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [22]:
#
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [23]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
#indexing and selection
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [26]:
#
mat[3,4]

np.int64(20)

In [27]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [28]:
mat[4]

array([21, 22, 23, 24, 25])

In [29]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat.sum()

np.int64(325)

In [31]:
#
np.std(mat)

np.float64(7.211102550927978)

In [32]:
mat.sum(0)

array([55, 60, 65, 70, 75])